version: "3.9"

services:
  db:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
    - "5431:5432"
    env_file:
      - .env